language: r
sudo: false
cache: packages
before_install:
- openssl aes-256-cbc -K $encrypted_ad3262635b9a_key -iv $encrypted_ad3262635b9a_iv -in tests/testthat/token.rds.enc -out tests/testthat/token.rds -d
r_packages:
- uuid
r_github_packages:
- jimhester/covr
env:
- warnings_are_errors: false
after_success:
- Rscript -e 'library(covr); coveralls()'
